### PR TITLE
View Synced Attendance

### LINKED ISSUE #63: View Synced  Attendance Information

### PR DESCRIPTION
**Pull request by Scott123180**
Attendance app V1

Fixes #63

### CODE REVIEW

**Review by vmjoseph — CHANGES_REQUESTED** [review]
I see that you have many commits in this merge request. Please refer to the wiki's [Project Management Page](https://github.com/Capping-CPCA/Web-App/wiki/Project-Management) under "#6  Rebase your "ready-to-be-reviewed" code" and  after you run the ```git rebase -i``` command, change all but one of your 'pick's to 'squash'. 

Also, please make sure you've rebased your branch onto develop so that your commit history matches up.

**Comment by sami10015** [comment]
Along with what Vallie said, pull requests should tend to be more atomic, meaning that it should be relatively smaller features with small commits, along with **descriptive** messages.  I personally recommend straying away from `git commit -m`, and just use `git commit` to open up Vim to enter in a better description. This helps the code reviewers look through and be able to understand exactly what you are doing, without having to delve deep into the code. Hope this tip helps.

**Review by sami10015 — CHANGES_REQUESTED** [review]
Along with what Vallie said, pull requests should tend to be more atomic, meaning that it should be relatively smaller features with small commits, along with **descriptive** messages.  I personally recommend straying away from `git commit -m`, and just use `git commit` to open up Vim to enter in a better description. This helps the code reviewers look through and be able to understand exactly what you are doing, without having to delve deep into the code. Hope this tip helps.

**Comment by Scott123180** [comment]
@vjoseph2 

I tried following the guidelines for rebasing the project, but I was running into many conflicts, often with my own branch. After a half hour I gave up and did a merge instead.

Any suggestions?

**Comment by blackjack26** [comment]
What you could always do which I've done many times is create a new branch off of develop (like `63-view-synced-attendance-2`. Add all of your changes in and then from that new branch do a `git push -f origin 63-view-synced-attendance-2:63-view-synced-attendance`. That will overwrite the commits with the stuff from the new branch while keeping the same branch name. Note that `git push -f` will delete anything you had originally on the branch so make sure you have a backup somewhere incase you forget to add something in.

**Comment by blackjack26** [comment]
Also, instead of doing `git commit -m "[comment]"` when developing. Do `git commit --amend` and that'll add it to your previous commit and make squashing at the end not needed at all since you'll only ever have one commit. (If you do push that commit though, when you do --amend you'll have to force push)

**Pull request closed without merging**
