### PR TITLE
Attendance Editing

### LINKED ISSUE #152: Attendance Editing
After creating a attendance form, can we add an edit before submitting the form? What if after making the instance of the class, they realize that they selected the wrong curriculum/location/etc.?

### LINKED ISSUE #166: Attendance, Age Validation >18
According to the PEP information available online and @algozine it's entirely possible for someone under 18 to be in classes.

https://github.com/Capping-CPCA/Web-App/blob/cbb61e3639aeca61be5e01bb22ed15e96bad4a91/public/js/attendance-scripts/attendance-form-add-new-person.js#L110

### PR DESCRIPTION
**Pull request by Scott123180**
- added new page for editing class information
- removed confirmation page for editing participants
- changed page permissions and routes for these pages

Fixes #152, Fixes #166

### CODE REVIEW

**Comment by Scott123180** [comment]
This is the exact same pull request from #173 . I had some git issues because I didn't amend my commits.

**Comment by Scott123180** [comment]
@blackjack26 @evanmena I've been reaching out over slack, any update? This is just the exact same PR as #173  plus now the conflict resolution in the routes

**Comment by blackjack26** [comment]
@Scott123180 Currently going through the pages to test it out first

**Comment by blackjack26** [comment]
I know this isn't something you changed, but when adding a participant from "No Intake Form" and setting the number of children to 0 doesn't add the participant or display an error that the participant couldn't be added. The reason it's not added is because the `validateNumChildren()` function returns a bad result.

<https://github.com/Capping-CPCA/Web-App/blob/152-attendance-editing/views/attendance/attendance_utilities.php#L174>

Calling the `empty()` function on a value that is either `''` or `0` will return true. Since we do allow them to put in `0` for number of children, we should check for that with something like:

```php
if (empty($num) && $num != 0) {
    // ...
}
```

@Scott123180 I can make the change real quick but I wanted to point it out to you

**Comment by Scott123180** [comment]
@blackjack26 
- fixed `empty()` issue
- also fixed age and numchildren validation to match JS validation

**Review by blackjack26 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
