### PR TITLE
Synced Attendance View

### LINKED ISSUE #63: View Synced  Attendance Information

### PR DESCRIPTION
**Pull request by Scott123180**
- Added view for synced attendance

Fixes #63

### CODE REVIEW

**Comment by sami10015** [comment]
You're missing a comment header on a couple of your JS files. One thing I would start doing a little bit more is making your comments **more descriptive**. 

Since PHP and JS are both dynamically typed languages, it is difficult to tell what type of parameters are being thrown into a function, and what type of data type is being returned. For example, in your JS file to add a new person, you have a function called validateFields:
```
function validateFields(first, middle, last, race, age, numChildren, zip){
     if(!validateName(first)){
         return "First name may only contain letters. Spaces, numbers, and other characters are not allowed.";
     }
     if(!validateMiddle(middle)){
         return "Middle initial may only contain one letter or nothing."
     }
     if(!validateName(last)){
         return "Last name may only contain letters. Spaces, numbers, and other characters are not allowed.";
     }
     if(!validateRace(race)){
         return "Please select a race from the drop-down."
     }
     if(!validateAge(age)){
         return "Please enter a valid age."
     }
     if(!validateNumChildren(numChildren)){
         return "Please enter a valid number of children"
     }
     if(!validateZip(zip)){
         return "Please enter a valid number zip";
     }
     //success
     return true;
 }
```
This and several of your other functions return different data types, so I would recommend adding comments above each function, listing the parameters/return values with their corresponding types as such _(This is PHP compared to above JS, but you get the idea)_:

```
    /**
     * Adds a route to be handled by the router
     * @param $url string the url associated with the route
     * @param $filename string the path to the page's filename (relative to /views)
     * @param $title string displayed on the top of the page when routed to
     */
    public function add($url, $filename, $title) {
        $this->routes[$url] = ["file" => $filename, "title" => $title];
    }
```

**Review by sami10015 — DISMISSED** [review]
Besides the documentation, I didn't catch an issue.

**Review by blackjack26 — CHANGES_REQUESTED** [review]
Rebase onto the current version of develop

**Comment by Scott123180** [comment]
I'm going to try to rebase later tonight. If I'm running into issues then I might need someone's help tomorrow morning during the deploy

**Pull request closed without merging**
