### PR TITLE
Fixed print capability on forms

### LINKED ISSUE #167: Print all forms
Functionality to print all forms:
- Intake Packet
- Referral Form
- Initial Contact / Self-Referral Form

### PR DESCRIPTION
**Pull request by stickzman**
Added css to print entire forms at once

Added print button to all forms

Fixes #167 

**Note**: While everything now prints, the fields are squashed and ugly. This is a separate formatting issue, and since it's referenced in #171, it will be tackled in a separate pull request.

### CODE REVIEW

**Review by christianmenk — APPROVED** [review]
Looks good to me, thanks so much for your help dude!

**Review by sbohner14335 — APPROVED** [review]
As long as the formatting is fixed before final deploy it looks good that everything is now displayed.

Thanks again!

**Comment by blackjack26** [comment]
Just a thought, it might look nicer (code-wise) to have all the print formatting in some `print.css` file that we just reference on the pages we want to use it. I'm not sure if the `@media print` stuff is the same or close to the same on each of the pages.

**Comment by stickzman** [comment]
@blackjack26 Agreed, but the CSS in these pages include a long workaround to a bug when trying to print collapsing panels in chrome. Not sure how/if this dump of CSS will affect other pages and that is why I chose to place it in these 3 pages individually.

**Comment by blackjack26** [comment]
@stickzman I agree that it shouldn't be all pages, all I mean is to dump it into a CSS file and maybe only reference it on those pages. I'm not 100% sure if there is a way to reference a CSS file from a `<style>`. If not then I think this is fine too.

**Comment by stickzman** [comment]
@blackjack26 yeah I couldn't figure out how to do that..

**Pull request merged**
